### ISSUE TITLE
이번 문제 set으로도 풀 수 있을 것 같아서 해보는데 잘 안됩니다  ㅜㅜ

### ISSUE THREAD

**Issue by leegyuho-programer** [CodeSprint01-TeamSix/LeetCode#27]
#26

**Comment by namminimi** [comment]
@leegyuho-programer 저도 Set함수 써서 해봤는데 이 코드 반환하는 값이 무조건 count 값이여야하고 카운트 숫자에 따라 output에 배열이 찍히더라고요 그래서 매개변수로 받은 배열에서 바로 요소 제거해줘야됩니다. 이번 문제에서는 set이나 filter 등등 못 쓸거같고 배열 요소 제거해주는 pop이나 splice, unshift? 등등 메서드를 사용하면 될 거 같습니다.
