### ISSUE TITLE
#32 제 풀이에서 어떤게 문제일까요? 일부 케이스 통과 안됨...

### ISSUE THREAD

**Issue by Jyophie** [CodeSprint01-TeamSix/LeetCode#33]
#32 해당 제 풀이의 경우에 어떤 부분이 문제인지 모르겠어요.
Run Code에서는 통과되었는데, Submit시 통과가 안되어서... 어떤 부분이 문제인걸까요 🤔

**Comment by An-jisu** [comment]
for문 아래에 i=0으로 초기화 해주는 표현식을 추가해주면 어떤가요??
[2,3,4,1,6] 인 경우에, profits=[3-2, 4-2] 까지 넣은 이후, 
i는 아직 0인 상태이다.
j가 3일 때는 (prices[3]=1 인 경우) 2<1 조건을 만족하지 않으므로, 이제서야 i가 1로 커진다. 그 후 다시 j=4가 된다. 
그러면, j=3일 때는 i=1인 경우에만 검사하고, i=2, i=3인 경우에는 검사하지 않게 되어,
로직에 빈틈이 생겨서 테케 통과하지 못하는 거 아닐까요?????
혹시 이해가 되시나요 ㅎㅎ...

즉, j에 비해 i는 특정 경우에만 증가하여, 모든 케이스에 대해서 검사를 하지 못한다!!!! 제 생각은 이렇습니다!!

그래서 저는 중첩 반복문으로 처리해주었는데, 시간 초과가 뜨네요..

**Comment by An-jisu** [comment]
혹시 통과되지 않는 테스트케이스는 무엇인지 알려주실 수 있을까요~!

**Comment by namminimi** [comment]
@An-jisu @Jyophie  저도 지수님과 같이 시간초과뜨네요 ㅋㅋㅋ  으아아아😫 이번에도.... 다른 블로그 참고해서 일단 올려두었습니다(코드 풀이도 야무지게 흑)

**Comment by Jyophie** [comment]
@An-jisu @namminimi 통과 안되는 테케 아래 케이스였어요!
지수님이 제안준 방법으로 시도해볼게요 :) 

https://leetcode.com/submissions/detail/1118676302/
